import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { GetServerSideProps } from "next";
import { GraphQLClient, gql } from "graphql-request";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

type Props = {
  exhibitions: Exhibitions[];
};

export default function Home({ exhibitions }: Props) {
  // console.log(`====> Exhibitions`, exhibitions);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        {exhibitions.map((exhibition) => (
          <li key={exhibition.slug}>
            <Link href={`/exhibitions/${exhibition.slug}`}>
              <h1>{exhibition.title}</h1>
            </Link>
          </li>
        ))}
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  const client = new GraphQLClient(process.env.NEXT_PUBLIC_GRAPHCMS_URL);
  const query = gql`
    query Exhibitions {
      exhibitions {
        date
        description
        id
        slug
        title
        content {
          html
        }
        image {
          id
          url(transformation: { image: { resize: { fit: max } } })
        }
      }
    }
  `;
  const data = await client.request(query);

  return {
    props: { exhibitions: data.exhibitions },
  };
};
